# Travis CI setup ITHACA-FV

sudo: required
dist: trusty
language: cpp

matrix:
  include:
  - name: "OpenFOAM 6"
    env: OF_VERS=6
  - name: "OpenFOAM 5"
    env: OF_VERS=5

before_install:
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam${OF_VERS}

install:
    - source /opt/openfoam${OF_VERS}/etc/bashrc
    - ./Allwmake -j

before_script:
    - source /opt/openfoam${OF_VERS}/etc/bashrc

script:
    - ./Allwmake -j

branches:    
    only:
        - master

